site_name: "Griffe"
site_description: "Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API."
site_url: "https://mkdocstrings.github.io/griffe"
repo_url: "https://github.com/mkdocstrings/griffe"
repo_name: "mkdocstrings/griffe"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src]
copyright: Copyright &copy; 2021 Timothée Mazzucotelli
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
not_in_nav: |
  usage.md

nav:
- Home: index.md
- Getting started:
  - getting-started.md
  - Installation: installation.md
  - Introduction: introduction.md
  - Playground: playground.md
  - License: license.md
  - Community:
    - community.md
    - Getting help: getting-help.md
    - Contributing: contributing.md
    - Code of conduct: code-of-conduct.md
    - Credits: credits.md
- Guide:
  - guide.md
  - User guide:
    - guide/users.md
    - Manipulating APIs:
      - Loading: guide/users/loading.md
      - Navigating: guide/users/navigating.md
      - Serializing: guide/users/serializing.md
      - Checking: guide/users/checking.md
      - Extending: guide/users/extending.md
    - Recommendations:
      - Public API: guide/users/public-api.md
      - Python code: guide/users/best-practices.md
      - Docstrings: guide/users/docstrings.md
  - Contributor guide:
    - guide/contributors.md
    - Environment setup: guide/contributors/setup.md
    - Management commands: guide/contributors/commands.md
    - Development workflow: guide/contributors/workflow.md
    - Architecture: guide/contributors/architecture.md
    - Coverage report: guide/contributors/coverage.md
- Reference:
  - reference.md
  - Command-line interface: reference/cli.md
  - Docstring parsers: reference/docstrings.md
  # TODO: Sprinkle all enumerations.
  - Python API:
    - reference/api.md
    - Loaders: reference/api/loaders.md
    - Finder: reference/api/finder.md
    - Models:
      - reference/api/models.md
      - Module: reference/api/models/module.md
      - Class: reference/api/models/class.md
      - Function: reference/api/models/function.md
      - Attribute: reference/api/models/attribute.md
      - Alias: reference/api/models/alias.md
    - Agents: reference/api/agents.md
    - API checks: reference/api/checks.md
    - Extensions: reference/api/extensions.md
    - Docstrings:
      - reference/api/docstrings.md
      - Models: reference/api/docstrings/models.md
      - Google: reference/api/docstrings/google.md
      - Numpy: reference/api/docstrings/numpy.md
      - Sphinx: reference/api/docstrings/sphinx.md
    - Exceptions: reference/api/exceptions.md
    - Expressions: reference/api/expressions.md
    - Git utilities: reference/api/git.md
    - Loggers: reference/api/loggers.md
    - Helpers: reference/api/helpers.md
- Changelog: changelog.md
- Insiders:
  - insiders/index.md
  - Getting started:
    - Installation: insiders/installation.md
    - Changelog: insiders/changelog.md
- Author's website: https://pawamoy.github.io/

theme:
  name: material
  custom_dir: docs/.overrides
  logo: logo.svg
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/custom.css
- css/mkdocstrings.css
- css/insiders.css

markdown_extensions:
- attr_list
- admonition
- callouts:
    strip_period: no
- footnotes
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec:
    ansi: required
- gen-files:
    scripts:
    - scripts/gen_griffe_json.py
    - scripts/redirects.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- coverage:
    page_path: guide/contributors/coverage
- mkdocstrings:
    handlers:
      python:
        import:
        - url: https://docs.python.org/3/objects.inv
          domains: [std, py]
        paths: [src, scripts, .]
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          extensions:
          - griffe_inherited_docstrings
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          separate_signature: true
          show_bases: false
          show_inheritance_diagram: true
          show_root_heading: true
          show_root_full_path: false
          show_source: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
- git-committers:
    enabled: !ENV [DEPLOY, false]
    repository: mkdocstrings/griffe
- minify:
    minify_html: !ENV [DEPLOY, false]
- group:
    enabled: !ENV [MATERIAL_INSIDERS, false]
    plugins:
    - typeset

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/mastodon
    link: https://fosstodon.org/@pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
  - icon: fontawesome/brands/gitter
    link: https://gitter.im/griffe/community
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/griffe/
